-- ==========================================================================
-- WEEK 1 PLSQL EXERCISES - BANKING SYSTEM
-- ==========================================================================

SET SERVEROUTPUT ON;

-- --------------------------------------------------------------------------
-- SETUP: CREATING TABLES AND SAMPLE DATA
-- --------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE AuditLog CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Transactions CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Accounts CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Loans CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Customers CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Employees CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DOB DATE,
    Balance NUMBER,
    LastModified DATE,
    IsVIP VARCHAR2(5) DEFAULT 'FALSE'
);

CREATE TABLE Accounts (
    AccountID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    AccountType VARCHAR2(20),
    Balance NUMBER,
    LastModified DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE Transactions (
    TransactionID NUMBER PRIMARY KEY,
    AccountID NUMBER,
    TransactionDate DATE,
    Amount NUMBER,
    TransactionType VARCHAR2(10),
    FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    LoanAmount NUMBER,
    InterestRate NUMBER,
    StartDate DATE,
    EndDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

CREATE TABLE Employees (
    EmployeeID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Position VARCHAR2(50),
    Salary NUMBER,
    Department VARCHAR2(50),
    HireDate DATE
);

CREATE TABLE AuditLog (
    LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(100)
);

INSERT INTO Customers (CustomerID, Name, DOB, Balance, LastModified) VALUES (1, 'John Doe', TO_DATE('1955-05-15', 'YYYY-MM-DD'), 12000, SYSDATE);
INSERT INTO Customers (CustomerID, Name, DOB, Balance, LastModified) VALUES (2, 'Jane Smith', TO_DATE('1990-07-20', 'YYYY-MM-DD'), 1500, SYSDATE);
INSERT INTO Accounts (AccountID, CustomerID, AccountType, Balance, LastModified) VALUES (1, 1, 'Savings', 10000, SYSDATE);
INSERT INTO Accounts (AccountID, CustomerID, AccountType, Balance, LastModified) VALUES (2, 2, 'Checking', 1500, SYSDATE);
INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (1, 1, SYSDATE, 200, 'Deposit');
INSERT INTO Transactions (TransactionID, AccountID, TransactionDate, Amount, TransactionType) VALUES (2, 2, SYSDATE, 300, 'Withdrawal');
INSERT INTO Loans (LoanID, CustomerID, LoanAmount, InterestRate, StartDate, EndDate) VALUES (1, 1, 5000, 5, SYSDATE, ADD_MONTHS(SYSDATE, 1));
INSERT INTO Employees (EmployeeID, Name, Position, Salary, Department, HireDate) VALUES (1, 'Alice Johnson', 'Manager', 70000, 'HR', TO_DATE('2015-06-15', 'YYYY-MM-DD'));
INSERT INTO Employees (EmployeeID, Name, Position, Salary, Department, HireDate) VALUES (2, 'Bob Brown', 'Developer', 60000, 'IT', TO_DATE('2017-03-20', 'YYYY-MM-DD'));
COMMIT;


-- --------------------------------------------------------------------------
-- EXERCISE 1: CONTROL STRUCTURES
-- --------------------------------------------------------------------------
-- Scenario 1 & 2
DECLARE
    CURSOR c1 IS SELECT CustomerID, DOB, Balance FROM Customers;
BEGIN
    FOR r IN c1 LOOP
        IF MONTHS_BETWEEN(SYSDATE, r.DOB)/12 > 60 THEN
            UPDATE Loans SET InterestRate = InterestRate - 1 WHERE CustomerID = r.CustomerID;
        END IF;
        IF r.Balance > 10000 THEN
            UPDATE Customers SET IsVIP = 'TRUE' WHERE CustomerID = r.CustomerID;
        END IF;
    END LOOP;
    COMMIT;
END;
/

-- Scenario 3
BEGIN
    FOR r IN (SELECT l.LoanID, c.Name, l.EndDate FROM Loans l JOIN Customers c ON l.CustomerID = c.CustomerID WHERE l.EndDate BETWEEN SYSDATE AND SYSDATE + 30) LOOP
        DBMS_OUTPUT.PUT_LINE('Reminder: Loan due for ' || r.Name);
    END LOOP;
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 2: ERROR HANDLING
-- --------------------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE PROCEDURE SafeTransferFunds(p_src NUMBER, p_dest NUMBER, p_amt NUMBER) AS
    v_bal NUMBER;
    v_fail EXCEPTION;
BEGIN
    SELECT Balance INTO v_bal FROM Accounts WHERE AccountID = p_src;
    IF v_bal < p_amt THEN RAISE v_fail; END IF;
    UPDATE Accounts SET Balance = Balance - p_amt WHERE AccountID = p_src;
    UPDATE Accounts SET Balance = Balance + p_amt WHERE AccountID = p_dest;
    COMMIT;
EXCEPTION
    WHEN v_fail THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: Insufficient funds');
END;
/

-- Scenario 2
CREATE OR REPLACE PROCEDURE UpdateSalary(p_id NUMBER, p_pct NUMBER) AS
BEGIN
    UPDATE Employees SET Salary = Salary + (Salary * (p_pct / 100)) WHERE EmployeeID = p_id;
    IF SQL%NOTFOUND THEN RAISE NO_DATA_FOUND; END IF;
    COMMIT;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Error: Employee not found');
END;
/

-- Scenario 3
CREATE OR REPLACE PROCEDURE AddNewCustomer(p_id NUMBER, p_name VARCHAR2, p_dob DATE, p_bal NUMBER) AS
BEGIN
    INSERT INTO Customers (CustomerID, Name, DOB, Balance, LastModified) VALUES (p_id, p_name, p_dob, p_bal, SYSDATE);
    COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Error: Customer already exists');
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 3: STORED PROCEDURES
-- --------------------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE PROCEDURE ProcessMonthlyInterest AS
BEGIN
    UPDATE Accounts SET Balance = Balance * 1.01 WHERE AccountType = 'Savings';
    COMMIT;
END;
/

-- Scenario 2
CREATE OR REPLACE PROCEDURE UpdateEmployeeBonus(p_dept VARCHAR2, p_bonus NUMBER) AS
BEGIN
    UPDATE Employees SET Salary = Salary + (Salary * (p_bonus / 100)) WHERE Department = p_dept;
    COMMIT;
END;
/

-- Scenario 3
CREATE OR REPLACE PROCEDURE TransferFunds(p_src NUMBER, p_dest NUMBER, p_amt NUMBER) AS
    v_bal NUMBER;
BEGIN
    SELECT Balance INTO v_bal FROM Accounts WHERE AccountID = p_src;
    IF v_bal >= p_amt THEN
        UPDATE Accounts SET Balance = Balance - p_amt WHERE AccountID = p_src;
        UPDATE Accounts SET Balance = Balance + p_amt WHERE AccountID = p_dest;
        COMMIT;
    END IF;
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 4: FUNCTIONS
-- --------------------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE FUNCTION CalculateAge(p_dob DATE) RETURN NUMBER AS
BEGIN
    RETURN TRUNC(MONTHS_BETWEEN(SYSDATE, p_dob) / 12);
END;
/

-- Scenario 2
CREATE OR REPLACE FUNCTION CalculateMonthlyInstallment(p_amt NUMBER, p_rate NUMBER, p_yrs NUMBER) RETURN NUMBER AS
    v_m NUMBER := p_yrs * 12;
    v_r NUMBER := (p_rate / 100) / 12;
BEGIN
    IF v_r = 0 THEN RETURN p_amt / v_m; END IF;
    RETURN (p_amt * v_r * POWER(1 + v_r, v_m)) / (POWER(1 + v_r, v_m) - 1);
END;
/

-- Scenario 3
CREATE OR REPLACE FUNCTION HasSufficientBalance(p_id NUMBER, p_amt NUMBER) RETURN BOOLEAN AS
    v_bal NUMBER;
BEGIN
    SELECT Balance INTO v_bal FROM Accounts WHERE AccountID = p_id;
    RETURN v_bal >= p_amt;
EXCEPTION
    WHEN OTHERS THEN RETURN FALSE;
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 5: TRIGGERS
-- --------------------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- Scenario 2
CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, LogDate, Action) VALUES (:NEW.TransactionID, SYSDATE, 'Insert');
END;
/

-- Scenario 3
CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW
DECLARE
    v_bal NUMBER;
BEGIN
    IF :NEW.Amount <= 0 THEN RAISE_APPLICATION_ERROR(-20002, 'Bad amount'); END IF;
    IF :NEW.TransactionType = 'Withdrawal' THEN
        SELECT Balance INTO v_bal FROM Accounts WHERE AccountID = :NEW.AccountID;
        IF v_bal < :NEW.Amount THEN RAISE_APPLICATION_ERROR(-20003, 'No balance'); END IF;
    END IF;
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 6: CURSORS
-- --------------------------------------------------------------------------
-- Scenario 1
DECLARE
    CURSOR c1 IS SELECT t.*, a.CustomerID FROM Transactions t JOIN Accounts a ON t.AccountID = a.AccountID WHERE TRUNC(t.TransactionDate, 'MM') = TRUNC(SYSDATE, 'MM');
BEGIN
    FOR r IN c1 LOOP
        DBMS_OUTPUT.PUT_LINE('Statement for Customer: ' || r.CustomerID || ' | Amount: ' || r.Amount);
    END LOOP;
END;
/

-- Scenario 2
DECLARE
    CURSOR c2 IS SELECT AccountID FROM Accounts FOR UPDATE;
BEGIN
    FOR r IN c2 LOOP
        UPDATE Accounts SET Balance = Balance - 25 WHERE CURRENT OF c2;
    END LOOP;
    COMMIT;
END;
/

-- Scenario 3
DECLARE
    CURSOR c3 IS SELECT LoanID FROM Loans FOR UPDATE;
BEGIN
    FOR r IN c3 LOOP
        UPDATE Loans SET InterestRate = InterestRate + 0.25 WHERE CURRENT OF c3;
    END LOOP;
    COMMIT;
END;
/


-- --------------------------------------------------------------------------
-- EXERCISE 7: PACKAGES
-- --------------------------------------------------------------------------
-- Scenario 1
CREATE OR REPLACE PACKAGE CustomerManagement AS
    PROCEDURE AddCustomer(p_id NUMBER, p_name VARCHAR2, p_dob DATE, p_bal NUMBER);
    FUNCTION GetBalance(p_id NUMBER) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY CustomerManagement AS
    PROCEDURE AddCustomer(p_id NUMBER, p_name VARCHAR2, p_dob DATE, p_bal NUMBER) AS
    BEGIN
        INSERT INTO Customers (CustomerID, Name, DOB, Balance, LastModified) VALUES (p_id, p_name, p_dob, p_bal, SYSDATE);
    END;
    FUNCTION GetBalance(p_id NUMBER) RETURN NUMBER AS
        v_bal NUMBER;
    BEGIN
        SELECT Balance INTO v_bal FROM Customers WHERE CustomerID = p_id;
        RETURN v_bal;
    END;
END;
/

-- Scenario 2
CREATE OR REPLACE PACKAGE EmployeeManagement AS
    PROCEDURE HireEmployee(p_id NUMBER, p_name VARCHAR2, p_pos VARCHAR2, p_sal NUMBER, p_dept VARCHAR2);
    FUNCTION GetAnnualSalary(p_id NUMBER) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY EmployeeManagement AS
    PROCEDURE HireEmployee(p_id NUMBER, p_name VARCHAR2, p_pos VARCHAR2, p_sal NUMBER, p_dept VARCHAR2) AS
    BEGIN
        INSERT INTO Employees(EmployeeID, Name, Position, Salary, Department, HireDate) VALUES (p_id, p_name, p_pos, p_sal, p_dept, SYSDATE);
    END;
    FUNCTION GetAnnualSalary(p_id NUMBER) RETURN NUMBER AS
        v_sal NUMBER;
    BEGIN
        SELECT Salary INTO v_sal FROM Employees WHERE EmployeeID = p_id;
        RETURN v_sal * 12;
    END;
END;
/

-- Scenario 3
CREATE OR REPLACE PACKAGE AccountOperations AS
    PROCEDURE OpenAccount(p_acc_id NUMBER, p_cust_id NUMBER, p_type VARCHAR2, p_bal NUMBER);
    FUNCTION TotalBalance(p_cust_id NUMBER) RETURN NUMBER;
END;
/

CREATE OR REPLACE PACKAGE BODY AccountOperations AS
    PROCEDURE OpenAccount(p_acc_id NUMBER, p_cust_id NUMBER, p_type VARCHAR2, p_bal NUMBER) AS
    BEGIN
        INSERT INTO Accounts(AccountID, CustomerID, AccountType, Balance, LastModified) VALUES (p_acc_id, p_cust_id, p_type, p_bal, SYSDATE);
    END;
    FUNCTION TotalBalance(p_cust_id NUMBER) RETURN NUMBER AS
        v_tot NUMBER;
    BEGIN
        SELECT SUM(Balance) INTO v_tot FROM Accounts WHERE CustomerID = p_cust_id;
        RETURN v_tot;
    END;
END;
/


-- --------------------------------------------------------------------------
-- OUTPUTS
-- --------------------------------------------------------------------------
/*
Reminder: Loan due for John Doe

Statement for Customer: 1 | Amount: 200
Statement for Customer: 2 | Amount: 300

Procedure SAFETRANSFERFUNDS compiled
Procedure UPDATESALARY compiled
Procedure ADDNEWCUSTOMER compiled
Procedure PROCESSMONTHLYINTEREST compiled
Procedure UPDATEEMPLOYEEBONUS compiled
Procedure TRANSFERFUNDS compiled
Function CALCULATEAGE compiled
Function CALCULATEMONTHLYINSTALLMENT compiled
Function HASSUFFICIENTBALANCE compiled
Trigger UPDATECUSTOMERLASTMODIFIED compiled
Trigger LOGTRANSACTION compiled
Trigger CHECKTRANSACTIONRULES compiled
Package CUSTOMERMANAGEMENT compiled
Package Body CUSTOMERMANAGEMENT compiled
Package EMPLOYEEMANAGEMENT compiled
Package Body EMPLOYEEMANAGEMENT compiled
Package ACCOUNTOPERATIONS compiled
Package Body ACCOUNTOPERATIONS compiled
*/